// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD0M0Ha3d9nizEIf9z2-xB7oK7qnOF4CM',
    appId: '1:563900351599:web:bea7f9e8ab1e215f15b99a',
    messagingSenderId: '563900351599',
    projectId: 'receiptbook-a6035',
    authDomain: 'receiptbook-a6035.firebaseapp.com',
    storageBucket: 'receiptbook-a6035.firebasestorage.app',
    measurementId: 'G-549LFXYGNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAckM8zAENQeXOqItgEh3lz-bEWEuw48rE',
    appId: '1:563900351599:android:46b3973c3ef3b35d15b99a',
    messagingSenderId: '563900351599',
    projectId: 'receiptbook-a6035',
    storageBucket: 'receiptbook-a6035.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0V50-6KB_ZimwyW-vvgo8C9ZDRDotCV4',
    appId: '1:563900351599:ios:a35a0c6e4ae542ed15b99a',
    messagingSenderId: '563900351599',
    projectId: 'receiptbook-a6035',
    storageBucket: 'receiptbook-a6035.firebasestorage.app',
    iosBundleId: 'com.example.receiptBookApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0V50-6KB_ZimwyW-vvgo8C9ZDRDotCV4',
    appId: '1:563900351599:ios:a35a0c6e4ae542ed15b99a',
    messagingSenderId: '563900351599',
    projectId: 'receiptbook-a6035',
    storageBucket: 'receiptbook-a6035.firebasestorage.app',
    iosBundleId: 'com.example.receiptBookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD0M0Ha3d9nizEIf9z2-xB7oK7qnOF4CM',
    appId: '1:563900351599:web:c967312573f953f215b99a',
    messagingSenderId: '563900351599',
    projectId: 'receiptbook-a6035',
    authDomain: 'receiptbook-a6035.firebaseapp.com',
    storageBucket: 'receiptbook-a6035.firebasestorage.app',
    measurementId: 'G-S9BFS1X5T2',
  );
}
